docr: add options get available regions subcommand
digitalocean/doctl pull request #1118
Opened 2022-03-03 16:23 UTC by CollinShoop

Depends on next release of godo including changes from https://github.com/digitalocean/godo/pull/516

2022-03-04 17:54 UTC, waynr approved these changes

2022-03-10 20:43 UTC, ChiefMateStarbuck requested changes
Hello @CollinShoop . In order to verify that the test will pass, this PR can be split into two PR's. 
1. Update godo version 
2. Add changes to registry

2022-03-10 20:50 UTC, CollinShoop commented
> Hello @CollinShoop . In order to verify that the test will pass, this PR can be split into two PR's.
> 
> 1. Update godo version
> 2. Add changes to registry

@ChiefMateStarbuck 👋🏻 I just updated the tests and they should pass now. Assuming everything passes, would you still prefer me to submit the vendor changes in a separate PR?

2022-03-10 20:53 UTC, ChiefMateStarbuck approved these changes
Good on Green.
Thank you @CollinShoop

2022-03-10 20:57 UTC, merged