Auth "init", "switch", "remove" Forces Lowercase
digitalocean/doctl pull request #1362
Opened 2023-03-31 19:39 UTC by danaelhe

**Background**
We've had several requests report that they are seeing a discrepancy in doctl authentication. When they create a context with an uppercase letter, the context name is stored in all lowercase and causes the following:
- When the context is used in uppercase, doctl accepts it but doesn't allow the authentication.
- When the context is used in lowercase, doctl accepts it and allows the authentication.

Currently, this is what happens:
```
$ doctl auth init --context Chandan
Please authenticate doctl for use with your DigitalOcean account. You can generate a token in the control panel at https://cloud.digitalocean.com/account/api/tokens

Enter your access token: 
Validating token... OK

$ doctl auth ls
chandan
default (current)

$ doctl auth switch --context Chandan
Now using context [Chandan] by default

$ doctl auth ls                  
chandan
default

$ doctl registry login
Error: Unable to initialize DigitalOcean API client: access token is required. (hint: run 'doctl auth init')

$ doctl auth switch --context chandan
Now using context [chandan] by default

$ doctl registry login           
Logging Docker in to registry.digitalocean.com  
```

In this code snippet, you can see that the context is created as Chandan but it is stored as chandan. When the context Chandan is used you can see it is accepted but the authentication fails. But when the context is used as chandan authentication works.

Ideally, when the uppercase context is used it should throw an error. This is an issue with Viper, a third party package doctl uses. This seems to be the most requested feature that the tool has yet to be supported:
https://github.com/spf13/viper/issues/1014

**Solution**
Though not ideal, I'm presenting a rather simple work around of lower-casing the `context` behind the scenes for the user and disclosing that the context names are case insensitive in the doctl man pages. With these changes, this is what would happen in the above scenario instead:

```
$ go run cmd/doctl/main.go auth init --context Sammy    
Please authenticate doctl for use with your DigitalOcean account. You can generate a token in the control panel at https://cloud.digitalocean.com/account/api/tokens

❯ Enter your access token:  ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

Validating token... ✔

$  go run cmd/doctl/main.go auth ls                      
default (current)
sammy
$  go run cmd/doctl/main.go auth switch --context Sammy
Now using context [sammy] by default
danaelhertani@C02DH08WMD6M doctl %  go run cmd/doctl/main.go auth ls                      
default
sammy (current)
$ go run cmd/doctl/main.go registry login 
Logging Docker in to registry.digitalocean.com
$  go run cmd/doctl/main.go auth ls                    
default
sammy (current)
$  go run cmd/doctl/main.go auth switch --context shark
Error: context does not exist
exit status 1
```

As you can see, the context is case insensitive now and can switch between existing contexts smoothly. It will also error when the context does not exist.

2023-04-10 14:41 UTC, scotchneat requested changes
Looks good so far.

Since the context flag can be included with any command (doesn't switch the context in the config), we'll also need to update the `getContextAccessToken` func in:
https://github.com/digitalocean/doctl/blob/main/commands/command_config.go#L136

It would also be good to consider tests to cover these cases.

2023-04-12 17:21 UTC, danaelhe commented
> Looks good so far.
> 
> Since the context flag can be included with any command (doesn't switch the context in the config), we'll also need to update the `getContextAccessToken` func in: https://github.com/digitalocean/doctl/blob/main/commands/command_config.go#L136
> 
> It would also be good to consider tests to cover these cases.

Thanks for the feedback. I was going back and forth on whether to make the "getContext" case insensitive. But I agree to it to truly make it a case insensitive experience throughout. 

The tests were a little tricky. You can't pass in the "context" arg like you would any other argument in doctl. So I tested what I could.

2023-04-12 21:00 UTC, scotchneat requested changes
This didn't work for me when using the flag (i.e. go run ./cmd/doctl --context TEST compute d ls). 

I left a different suggestion that resolves it inline.

2023-04-13 04:14 UTC, danaelhe commented on commands/command_config.go
>  			token := ""
oh good catch!! Didn't think about that scenario. Added the commit.

2023-04-13 14:15 UTC, scotchneat approved these changes
LGTM 👍🏽

2023-04-13 17:41 UTC, merged