DBAAS Kafka Topics Support
digitalocean/doctl pull request #1457
Opened 2023-11-02 00:37 UTC by dweinshenker

**What**

- Adds support for CRUD operations on kafka topics, partitions
- Supports advanced configuration for kafka topics

2023-11-16 20:25 UTC, danaelhe requested changes
Looks great! Just some minor nitpicks on documentation.

2023-11-16 20:25 UTC, danaelhe commented on commands/databases.go
> +	cmdDatabaseTopicUpdate := CmdBuilder(cmd, RunDatabaseTopicUpdate, "update <database-id>", "Updates a topic for a given kafka database",
```suggestion
	cmdDatabaseTopicUpdate := CmdBuilder(cmd, RunDatabaseTopicUpdate, "update <database-uuid> <topic-name>", "Updates a topic for a given kafka database",
```

2023-11-16 20:25 UTC, danaelhe commented on commands/databases.go
> +		"This command creates a kafka topic for the specified kafka database cluster, giving it the specified name. Example: doctl databases topics create <cluster_uuid> <topic_name>", Writer, aliasOpt("c"
```suggestion
		"This command creates a kafka topic for the specified kafka database cluster, giving it the specified name. Example: doctl databases topics create <database-uuid> <topic-name> --replication_factor 2 --partition_count 4", Writer, aliasOpt("c"))
```

2023-11-16 20:25 UTC, danaelhe commented on commands/databases.go
> +	cmdDatabaseTopicDelete := CmdBuilder(cmd, RunDatabaseTopicDelete, "delete <database-id> <topic-name>", "Deletes a kafka topic by topic name", "", Writer, aliasOpt("rm"))
```suggestion
	cmdDatabaseTopicDelete := CmdBuilder(cmd, RunDatabaseTopicDelete, "delete <database-uuid> <topic-name>", "Deletes a kafka topic by topic name", "", Writer, aliasOpt("rm"))
```

2023-11-16 20:25 UTC, danaelhe commented on commands/databases.go
> +	CmdBuilder(cmd, RunDatabaseTopicGet, "get <database-id> <topic-name>", "Retrieve the configuration for a given kafka topic", topicGetDetails, Writer, displayerType(&displayers.DatabaseKafkaTopic{}),
```suggestion
	CmdBuilder(cmd, RunDatabaseTopicGet, "get <database-uuid> <topic-name>", "Retrieve the configuration for a given kafka topic", topicGetDetails, Writer, displayerType(&displayers.DatabaseKafkaTopic{}), aliasOpt("g"))
```

2023-11-16 20:25 UTC, danaelhe commented on commands/databases.go
> +	CmdBuilder(cmd, RunDatabaseTopicList, "list <database-id>", "Retrieve a list of topics for a given kafka database", topicListDetails, Writer, displayerType(&displayers.DatabaseKafkaTopics{}), aliasO
```suggestion
	CmdBuilder(cmd, RunDatabaseTopicList, "list <database-uuid>", "Retrieve a list of topics for a given kafka database", topicListDetails, Writer, displayerType(&displayers.DatabaseKafkaTopics{}), aliasOpt("ls"))
```

2023-11-16 20:25 UTC, danaelhe commented on commands/databases.go
> +		"This command updates a kafka topic for the specified kafka database cluster. Example: doctl databases topics update <cluster_uuid> <topic_name>", Writer, aliasOpt("u"))
```suggestion
		"This command updates a kafka topic for the specified kafka database cluster. Example: doctl databases topics update <database-uuid> <topic-name>", Writer, aliasOpt("u"))
```

2023-11-17 16:46 UTC, dweinshenker commented
Thanks for the thorough review @danaelhe! agreed with all your suggestions for documentation and made those commits.

2023-11-17 16:49 UTC, danaelhe approved these changes
Looks great! Thank you so much 🚢

2023-11-17 16:49 UTC, merged