[DBAAS] | Add API endpoint for applying cluster patches
digitalocean/doctl pull request #1579
Opened 2024-09-11 13:48 UTC by vsharma6855

2024-09-12 14:22 UTC, loosla commented
Thanks for your contribution :rocket:  

I believe we are using hyphen instead of underscores (install_update) in commands names. 
Maybe just `update` can be clear enough as a name? 
I'd rely on @andrewsomething as he may share more thoughts about the naming.

2024-09-12 15:23 UTC, andrewsomething requested changes

2024-09-12 15:23 UTC, andrewsomething commented on commands/databases.go
> +	cmdDatabaseInstallUpdate := CmdBuilder(cmd, RunDatabaseInstallUpdate, "install_update <database-cluster-id>", "Starts installation of updates ", "Starts installation of updates ", Writer)
Here you create a new `install_update` sub-group under `databases` and add an `install_update` command to it. So to use this command, you must run:

    doctl databases install_update install_update <database-cluster-id> 

Instead, I think grouping this with the existing maintenance window commands might make a lot of sense. It keeps sub-commands related to applying updates together. So we'd have something like:

```
$ doctl databases maintenance-window -h

# ...

Available Commands:
  get         Retrieve details about a database cluster's maintenance windows
  update      Update the maintenance window for a database cluster
  install     Start installation of updates for a database cluster outside of a maintenance window
```

If we attach it to the top-level `databases` command, please use `install-update` with a hyphen not an underscore for consistency with other commands.

2024-09-17 14:22 UTC, loosla commented
Looks good to me :+1:

2024-09-17 15:39 UTC, andrewsomething approved these changes
:+1:  LGTM

2024-09-17 15:44 UTC, merged