ISSUE: 1585
digitalocean/doctl pull request #1590
Opened 2024-10-08 15:51 UTC by Yordaniss

* added bool flag into resize command
* added wait functionality into resize
* adjusted test

2024-10-08 21:57 UTC, andrewsomething requested changes
Hi @Yordaniss. Thank you so much for the pull request!

I've left a few comments in-line with suggestions. In addition to that, it would be great to add a new test case to the `TestDatabaseResize` test. 
https://github.com/digitalocean/doctl/blob/6804c7d62dfd7ff142ddb3ac1abed3893f9cdcab/commands/databases_test.go#L618

Something along the line of:

```go
	// Success with wait flag
	withTestClient(t, func(config *CmdConfig, tm *tcMocks) {
		tm.databases.EXPECT().Resize(testDBCluster.ID, r).Return(nil)
		tm.databases.EXPECT().Get(testDBCluster.ID).Return(&testDBCluster, nil)
		config.Args = append(config.Args, testDBCluster.ID)
		config.Doit.Set(config.NS, doctl.ArgSizeSlug, testDBCluster.SizeSlug)
		config.Doit.Set(config.NS, doctl.ArgDatabaseNumNodes, testDBCluster.NumNodes)
		config.Doit.Set(config.NS, doctl.ArgDatabaseStorageSizeMib, testDBCluster.StorageSizeMib)
		config.Doit.Set(config.NS, doctl.ArgCommandWait, true)

		err := RunDatabaseResize(config)
		assert.NoError(t, err)
	})
```

Comparing that to the existing tests, you'll see it passes the `wait` flag and tests that the `Get` method is called by `waitForDatabaseReady` when the flag is passed.

Let us know if you have any questions!

2024-10-08 21:57 UTC, andrewsomething commented on commands/databases.go
> +	}
I think that we could probably simplify this a bit further. Compared to the create command, the resize command only returns success or error. It doesn't output the database information. So we can remove this call to `Get` here as well as the one below in the `wait` block.

2024-10-08 21:57 UTC, andrewsomething commented on commands/databases.go
> +	return displayDatabases(c, false, *db)
```suggestion
		notice("Database resized successfully")
	}

	return nil
```

Let's also move the notice inside the wait block. That way the current behavior remains the same if you do not pass the `--wait` flag.

2024-10-09 07:20 UTC, Yordaniss commented
Hi @andrewsomething thanks a lot for a feedback. I simplified logic and added test case. 🙂

2024-10-09 20:08 UTC, andrewsomething approved these changes
:+1:  Great work! Thanks again for the contribution!

2024-10-09 20:12 UTC, merged