Add support for getting Droplets by name
digitalocean/doctl pull request #898
Opened 2020-10-24 16:52 UTC by mamercad

Might fix #895 -- I'm not very experienced in Golang.

```
❯ ./builds/doctl compute droplet list
ID           Name             Public IPv4       Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image                     VPC UUID                                Status    Tags    Features              Volumes
213635352    hacktoberfest    142.93.240.125    10.116.0.2                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking    
213653028    hacktoberfest    142.93.5.117      10.116.0.3                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking
```

```
❯ ./builds/doctl compute droplet get hacktoberfest
Error: Multiple Droplets with the name "hacktoberfest" found.
```

```
❯ ./builds/doctl compute droplet delete 213653028
Warning: Are you sure you want to delete this Droplet? (y/N) ? y
```

New functionality:
```
❯ ./builds/doctl compute droplet get hacktoberfest
ID           Name             Public IPv4       Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image                     VPC UUID                                Status    Tags    Features              Volumes
213635352    hacktoberfest    142.93.240.125    10.116.0.2                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking
```

```
❯ ./builds/doctl compute droplet delete 213635352
Warning: Are you sure you want to delete this Droplet? (y/N) ? y
```

```
❯ ./builds/doctl compute droplet get hacktoberfest
Error: Droplet with the name "hacktoberfest" could not be found.
```

2020-10-26 18:51 UTC, andrewsomething requested changes
Thanks for taking this on @mamercad!

In order to reduce some duplication, I think it would be best to reuse the existing `matchDroplets` function that is called when deleting by name.

https://github.com/digitalocean/doctl/blob/master/commands/droplets.go#L516

You can see how it gets used by the delete command here:

https://github.com/digitalocean/doctl/blob/master/commands/droplets.go#L501-L509

2020-10-27 11:54 UTC, mamercad commented
This isn't right, still working on it.

2020-10-27 12:02 UTC, mamercad commented
```
❯ ./builds/doctl compute droplet list
ID           Name             Public IPv4        Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image                     VPC UUID                                Status    Tags    Features              Volumes
213989132    hacktoberfest    67.205.153.187     10.116.0.2                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking    
214047592    hacktoberfest    167.172.148.146    10.116.0.3                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking    
214049768    test             157.230.215.122    10.116.0.4                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking    

❯ ./builds/doctl compute droplet get hacktoberfest
Error: There are 2 Droplets with the name "hacktoberfest"; please provide a specific Droplet ID. [213989132, 214047592]

❯ ./builds/doctl compute droplet get test
ID           Name    Public IPv4        Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image                     VPC UUID                                Status    Tags    Features              Volumes
214049768    test    157.230.215.122    10.116.0.4                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking
```

Seems to work now.

2020-10-27 15:44 UTC, andrewsomething requested changes

2020-10-27 15:44 UTC, andrewsomething commented on commands/droplets.go
>  	if err != nil {
This check can be removed. It always results in an error when passing a string. `getDropletIDArg` ensures that only one argument is provided and that it is an integer. Now that integers and strings are valid arguments, the check you added below will be enough to validate input.

2020-10-27 15:44 UTC, andrewsomething commented on commands/droplets.go
> +		if len(c.Args) < 1 {
```suggestion
		if len(c.Args) != 1 {
```

The get command only returns one result, so should only accept one argument.

2020-10-27 15:44 UTC, andrewsomething commented on commands/droplets.go
> +		}
Some of this is still duplicating some of what `matchDroplets` provides. The "anonymous" function here that is passed to `matchDroplets`, is called with a list of IDs which have already had the conversion from name to ID. This also duplicates the `ds.Get(id)` further below, adding another network request.

It's probably a bit cleaner to move the display logic into the function and just return the call to `matchDroplets` at the end.

```go
	fn := func(ids []int) error {
		for _, id := range ids {
			d, err := ds.Get(id)
			if err != nil {
				return err
			}

			item := &displayers.Droplet{Droplets: do.Droplets{*d}}
			if getTemplate != "" {
				t := template.New("Get template")
				t, err = t.Parse(getTemplate)
				if err != nil {
					return err
				}
				return t.Execute(c.Out, d)
			}
			return c.Display(item)
		}
		return nil
	}

	return matchDroplets(c.Args, ds, fn)
```

2020-10-27 21:33 UTC, mamercad commented
```
❯ ./builds/doctl compute droplet list | grep test
214119531    test1                               64.227.3.17        10.116.0.6                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64        0c20a2e6-b9ca-43fd-8b22-def8741321ac    active                                                               private_networking    
214119620    test1                               134.122.117.15     10.116.0.7                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64        0c20a2e6-b9ca-43fd-8b22-def8741321ac    active                                                               private_networking    
214119947    test2                               157.230.232.122    10.116.0.8                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64        0c20a2e6-b9ca-43fd-8b22-def8741321ac    new                                                                  private_networking    

❯ ./builds/doctl compute droplet get test2
ID           Name     Public IPv4        Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image                     VPC UUID                                Status    Tags    Features              Volumes
214119947    test2    157.230.232.122    10.116.0.8                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking    

❯ ./builds/doctl compute droplet get test1
Error: There are 2 Droplets with the name "test1"; please provide a specific Droplet ID. [214119531, 214119620]

❯ ./builds/doctl compute droplet get 214119531
ID           Name     Public IPv4    Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image                     VPC UUID                                Status    Tags    Features              Volumes
214119531    test1    64.227.3.17    10.116.0.6                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking
```

2020-10-28 20:31 UTC, mamercad reviewed
Ah, thanks for helping me, again!

2020-10-28 20:44 UTC, andrewsomething approved these changes
:+1:  Thanks again for this! Just waiting for Travis to go green (queue times have been very long recently).

2020-10-28 21:18 UTC, merged