registry - generate a DOSecret operator friendly secret manifest
digitalocean/doctl pull request #966
Opened 2021-03-08 22:39 UTC by varshavaradarajan

The Kubernetes secret manifest  we generate makes it easy for users to pull private images into their DOKS cluster. Now that we have the dosecret-operator to make the secret available in all namespaces, generate operator friendly manifests for users to apply into their DOKS cluster. Applying the manifest generated here to a DOKS cluster is the same as doing:

```
doctl kubernetes cluster registry add
```

cc @adamwg , @timoreimann

2021-03-09 00:09 UTC, andrewsomething requested changes
Looks like this integration test will need to be updated as well:

https://github.com/digitalocean/doctl/blob/1cb9bf9e8a414defa40fbeb2d85448fbc73dbb87/integration/registry_kubernetes_manifest_test.go#L84-L95

Unfortunately, it doesn't seem to have run in this PR. I've identified and fixed the issue preventing it from running in: https://github.com/digitalocean/doctl/pull/967

2021-03-09 18:37 UTC, andrewsomething commented
If you rebase on main, you'll see the failure:

```
=== CONT  TestRun/doctl/registry/kubernetes-manifest/prints_a_kubernetes_manifest_for_a_secret_with_the_registry_credentials
    registry_kubernetes_manifest_test.go:78: 
        	Error Trace:	registry_kubernetes_manifest_test.go:78
        	            				spec.go:269
        	            				spec.go:262
        	            				parser.go:133
        	Error:      	Not equal: 
        	            	expected: map[string]interface {}{"apiVersion":"v1", "data":map[string]interface {}{".dockerconfigjson":"eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJZamRrTUROaE5qazBOMkl5TVRkbFptSTJaak5sWXpOaVpETTFNRFExT0RJNllqZGtNRE5oTmprME4ySXlNVGRsWm1JMlpqTmxZek5pWkRNMU1EUTFPRElLIn19fQ=="}, "kind":"Secret", "metadata":map[string]interface {}{"creationTimestamp":interface {}(nil), "name":"registry-my-registry", "namespace":"default"}, "type":"kubernetes.io/dockerconfigjson"}
        	            	actual  : map[string]interface {}{"apiVersion":"v1", "data":map[string]interface {}{".dockerconfigjson":"eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJZamRrTUROaE5qazBOMkl5TVRkbFptSTJaak5sWXpOaVpETTFNRFExT0RJNllqZGtNRE5oTmprME4ySXlNVGRsWm1JMlpqTmxZek5pWkRNMU1EUTFPRElLIn19fQ=="}, "kind":"Secret", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"digitalocean.com/dosecret-identifier":"registry-my-registry"}, "creationTimestamp":interface {}(nil), "name":"registry-my-registry", "namespace":"kube-system"}, "type":"kubernetes.io/dockerconfigjson"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -6,6 +6,9 @@
        	            	  (string) (len=4) "kind": (string) (len=6) "Secret",
        	            	- (string) (len=8) "metadata": (map[string]interface {}) (len=3) {
        	            	+ (string) (len=8) "metadata": (map[string]interface {}) (len=4) {
        	            	+  (string) (len=11) "annotations": (map[string]interface {}) (len=1) {
        	            	+   (string) (len=36) "digitalocean.com/dosecret-identifier": (string) (len=20) "registry-my-registry"
        	            	+  },
        	            	   (string) (len=17) "creationTimestamp": (interface {}) <nil>,
        	            	   (string) (len=4) "name": (string) (len=20) "registry-my-registry",
        	            	-  (string) (len=9) "namespace": (string) (len=7) "default"
        	            	+  (string) (len=9) "namespace": (string) (len=11) "kube-system"
        	            	  },
        	Test:       	TestRun/doctl/registry/kubernetes-manifest/prints_a_kubernetes_manifest_for_a_secret_with_the_registry_credentials
```

2021-03-09 20:29 UTC, timoreimann submitted a review, later dismissed
Grammar nit, otherwise looks good from a DOKS perspective (given it passes the integration tests that Andrew fixed).

2021-03-09 22:54 UTC, andrewsomething submitted a review, later dismissed
:+1:  Looks good!

Question: Is the operator being back-filled onto existing clusters? Do we need any caveats about cluster versions in the help text?

2021-03-10 00:37 UTC, varshavaradarajan commented
@andrewsomething - Good point! We have backfilled the operator until `1.15.12-do.2`. Since this command is cluster-agnostic, what do you suggest we do? The manifest that this change generates for `kube-system` namespace or by default will trigger the operator in versions > 1.15.12-do.2. For unsupported versions, the manifest is harmless. For other namespaces, the manifest will be generated same as before.

2021-03-16 14:50 UTC, andrewsomething approved these changes
:+1:

2021-03-16 14:50 UTC, merged